name: style_guide_analysis
description: Linter rules for Flutter style guide.
# version: 1.0.0
# homepage: https://www.example.com

environment:
  sdk: '>=2.7.0 <3.0.0'

dependencies:
  analyzer: ^0.39.2+1

dev_dependencies:
  pedantic: ^1.8.0
  test: ^1.6.0
